ACMS-4329: Temp run github CI.

diff --git a/.github/workflows/deployment.workflow.yml b/.github/workflows/deployment.workflow.yml
--- a/.github/workflows/deployment.workflow.yml
+++ b/.github/workflows/deployment.workflow.yml
@@ -1,7 +1,7 @@
-name: "Code Deployment on Acquia Environment"
+name: "Code Deployment (Acquia)"
 on:
   push:
-    branches: [ develop ]
+    branches: [ develop, ACMS-4329 ]
   workflow_dispatch:
     inputs:
       environment:
@@ -23,7 +23,7 @@ on:
         required: true
         default: 'dev'
       drupal-core:
-        description: 'Choose Drupal Core'
+        description: 'Choose Drupal Core Version'
         required: true
         default: '^11'
       php-version:
@@ -36,6 +36,10 @@ on:
           - "8.4"
         required: true
         default: '8.3'
+      download-latest-dependencies:
+        description: 'Download latest dependencies'
+        type: boolean
+        default: false
 
 concurrency:
   group: "ci-${{ github.ref }}"
@@ -47,8 +51,9 @@ env:
   GIT_COMMITTER_EMAIL: "no-reply@acquia.com"
   GIT_AUTHOR_EMAIL: "no-reply@acquia.com"
   PHP_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.php-version || '8.3' }}
-  CORE_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.drupal-core || '^11' }}
+  CORE_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.drupal-core || '' }}
   ACQUIA_CLOUD_ENVIRONMENT: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
+  DOWNLOAD_LATEST_DEPENDENCIES: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.download-latest-dependencies || 'false' }}
 
 jobs:
   acquia_code_deployment:
@@ -88,12 +93,24 @@ jobs:
           ACQUIA_CLOUD_KNOWN_HOSTS: ${{ vars.ACQUIA_CLOUD_KNOWN_HOSTS }}
       - name: Setup Drupal Project
         run: |
-          # Install specific version of Drupal Core.
-          composer require drupal/core:${CORE_VERSION} drupal/core-composer-scaffold:${CORE_VERSION} drupal/core-recommended:${CORE_VERSION} --no-install --no-update -n
+          # Download specific version of Drupal Core, if requested.
+          [ -n "${CORE_VERSION}" ] && echo composer require drupal/core:${CORE_VERSION} drupal/core-composer-scaffold:${CORE_VERSION} drupal/core-recommended:${CORE_VERSION} --no-install --no-update -n || true
 
-          # Move some of development dependencies to production depencies or else acli push:artifact will fail.
+          # Move some of development dependencies to production dependencies or else acli push:artifact will fail.
           composer require oomphinc/composer-installers-extender --no-install --no-update -n
-          composer update "drupal/core-*" drush/drush "drupal/*" -W --with=drupal/core:${CORE_VERSION} --minimal-changes
+
+          if [ "${DOWNLOAD_LATEST_DEPENDENCIES}" == "true" ]; then
+            rm composer.lock
+            composer install
+          else
+            # Update specific version of Drupal Core, if requested or else simply install all dependencies.
+            if [ -n "${CORE_VERSION}" ]; then
+              composer update "drupal/core-*" drush/drush "drupal/*" -W --with=drupal/core:${CORE_VERSION} --minimal-changes
+            else
+              # In CI, we don't need to run composer install again, as it's already will be done by below command.
+              composer update oomphinc/composer-installers-extender
+            fi
+          fi
 
           # Include MySQL 5.7 connection settings, before DRS require line is added.
           echo "require DRUPAL_ROOT . '/modules/contrib/mysql57/settings.inc';" >> docroot/sites/default/settings.php
@@ -128,11 +145,13 @@ jobs:
         run: |
           # Find the PHP version.
           ENV_PHP_VERSION=$(acli api:environments:find ${ACQUIA_CLOUD_APPLICATION}.${ACQUIA_CLOUD_ENVIRONMENT} -n | jq -r '.configuration.php.version')
-          echo $ENV_PHP_VERSION
-          exit 1
+          echo "The CI php-version: ${PHP_VERSION}"
+          echo "The Acquia Cloud environment php-version: $ENV_PHP_VERSION"
           # If PHP_VERSION is NOT the same as the one we want to switch to. Then switch PHP version.
           if [ "${ENV_PHP_VERSION}" != "${PHP_VERSION}" ]; then
-            acli api:environments:update ${ACQUIA_CLOUD_APPLICATION}.${ACQUIA_CLOUD_ENVIRONMENT} --lang_version=${PHP_VERSION} -n
+             echo "Switching PHP version to ${PHP_VERSION}"
+             acli api:environments:update ${ACQUIA_CLOUD_APPLICATION}.${ACQUIA_CLOUD_ENVIRONMENT} --lang_version=${PHP_VERSION} -n
+             sleep 10
           fi
       - name: Deploy & Switch Code
         shell: bash
